##################################################
# Authors : 
#     Andrea Galimberti (andrea.galimberti@polimi.it),
#     Davide Galli (davide.galli@polimi.it),
#     Davide Zoni (davide.zoni@polimi.it)
#     
# Other contributor(s):  
#     Francesco Lattari
##################################################

user: 
token: 
project: 