##################################################
# Authors : 
#     Andrea Galimberti (andrea.galimberti@polimi.it),
#     Davide Galli (davide.galli@polimi.it),
#     Davide Zoni (davide.zoni@polimi.it)
#     
# Other contributor(s):  
#     Francesco Lattari
##################################################

experiment:
  name: AesAscad
  cipher: AES
  log_dir: #"/path/to/log/experiment/"
  neptune_config_file: attack/CNN/configs/common/neptune_configs.yaml
  checkpoint:
    monitor: valid/guessing_entropy
  early_stop:
    name: EarlyStopping
    config:
      monitor: valid/loss
      patience: 10
      mode: min
      check_finite: True
  trainer:
    max_epochs: 50
    check_val_every_n_epoch: 1
    log_every_n_steps: 4
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
  tags:
    - ASCAD
    - 5_blocks
    - conv1d
    - 50epochs
    - byte0
